# Generated by Django 4.2.11 on 2024-03-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garage',
            name='is_parking_available',
            field=models.BooleanField(default=True),
        ),
    ]
